apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekforge-build
  namespace: tekforge
  annotations:
    iam.gke.io/gcp-service-account: tekforge-builder@REPLACE_PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekforge-deployer
  namespace: tekforge
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekforge-deployer
  namespace: tekforge
subjects:
  - kind: ServiceAccount
    name: tekforge-build
    namespace: tekforge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekforge-deployer
